# 服务配置
server:
  port: 9696
  servlet:
    # 接口全局路径前缀
    context-path: /api

# Spring 配置
spring:
  # redis 配置
  redis:
    port: 6379
    host: 192.168.111.129
    password: 123456
    connect-timeout: 5000
    database: 1
  application:
    name: user-center
  # 数据库配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/user_center_db
    username: root
    password: 123456
  # session 配置
  session:
    timeout: 60
    store-type: redis

# mybatis plus 配置
mybatis-plus:
  global-config:
    db-config:
      # 数据库表前缀
      table-prefix: tb_
      # 数据库表字段逻辑删除
      logic-delete-field: isDelete
      logic-delete-value: 1
      logic-not-delete-value: 0
  configuration:
    # 日志打印输出
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

# 接口文档配置
# springdoc-openapi项目配置
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: com.me.usercenter.controller
# knife4j的增强配置
knife4j:
  enable: true
  setting:
    language: zh_cn

